title: "Christian Brüggemann"

markdown: kramdown

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - blog
  - static
  - "*.html"

jekyll-spaceship:
  mermaid-processor:
    syntax:
      code: 'mermaid'