title: "Christian Brüggemann"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - blog
  - static
  - "*.html"

jekyll-spaceship:
  mermaid-processor:
    syntax:
      code: 'mermaid'

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
    span:
      line_numbers: false
